name: "Terraform"
#testttttttttt
on:
  push:
    branches:
      - main
  pull_request:

jobs: 
  terraform:  
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        id: fmt
        name: "Terraform Format"
        run: "terraform fmt -check"
        continue-on-error: true
      - 
        id: init
        name: "Terraform Init"
        run: "terraform init"
      - 
        id: validate
        name: "Terraform Validate"
        run: "terraform validate -no-color"
      -
        id: plan
#         if: "github.event_name == 'pull_request'"
        name: "Terraform Show"
        run: "terraform plan" 
        env: 
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      -
        name: "Terraform Apply"
        run: "terraform apply -auto-approve"
        env: 
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
